"""empty message

Revision ID: 35da916c357b
Revises: a995cd987ed8
Create Date: 2021-08-31 10:38:17.729011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35da916c357b'
down_revision = 'a995cd987ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pregunta', sa.Column('feRespuesta', sa.Date(), nullable=True))
    op.drop_column('pregunta', 'ferespuesta')
    op.add_column('servicio', sa.Column('txCredenciales', sa.String(length=1000), nullable=True))
    op.add_column('servicio', sa.Column('foto', sa.String(length=100), nullable=False))
    op.drop_index('idsUsrVende', table_name='servicio')
    op.create_unique_constraint(None, 'servicio', ['foto'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio', type_='unique')
    op.create_index('idsUsrVende', 'servicio', ['idUsrVende'], unique=False)
    op.drop_column('servicio', 'foto')
    op.drop_column('servicio', 'txCredenciales')
    op.add_column('pregunta', sa.Column('ferespuesta', sa.DATE(), nullable=True))
    op.drop_column('pregunta', 'feRespuesta')
    # ### end Alembic commands ###
