"""empty message

Revision ID: 4a559d81b2c5
Revises: 
Create Date: 2021-08-23 19:54:12.653685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a559d81b2c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreCategoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feContrato', sa.Date(), nullable=True),
    sa.Column('puntosVendedor', sa.Integer(), nullable=False),
    sa.Column('puntosComprador', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreEstado', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forma_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formaPago', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreMunicipio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feFacturacion', sa.Date(), nullable=True),
    sa.Column('montoPago', sa.Float(), nullable=True),
    sa.Column('fePago', sa.Date(), nullable=True),
    sa.Column('statusPago', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombrePlan', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=200), nullable=True),
    sa.Column('fePregunta', sa.Date(), nullable=True),
    sa.Column('respuesta', sa.String(length=200), nullable=True),
    sa.Column('ferespuesta', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreServicio', sa.String(length=100), nullable=False),
    sa.Column('fePublicacion', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('statusServicio', sa.Integer(), nullable=False),
    sa.Column('inDomicilio', sa.Boolean(), nullable=False),
    sa.Column('palabrasClave', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logUsr', sa.String(length=100), nullable=False),
    sa.Column('nombreUsr', sa.String(length=100), nullable=False),
    sa.Column('claveUsr', sa.String(length=50), nullable=False),
    sa.Column('correoUsr', sa.String(length=100), nullable=False),
    sa.Column('feRegistro', sa.Date(), nullable=False),
    sa.Column('txCredenciales', sa.String(length=1000), nullable=True),
    sa.Column('rankVendedor', sa.Integer(), nullable=True),
    sa.Column('rankComprador', sa.Integer(), nullable=True),
    sa.Column('foto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correoUsr'),
    sa.UniqueConstraint('foto'),
    sa.UniqueConstraint('logUsr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('user')
    op.drop_table('servicio')
    op.drop_table('pregunta')
    op.drop_table('plan')
    op.drop_table('pago')
    op.drop_table('municipio')
    op.drop_table('forma_pago')
    op.drop_table('favorito')
    op.drop_table('estado')
    op.drop_table('contrato')
    op.drop_table('categoria')
    # ### end Alembic commands ###
